spring:
  application:
    name: courses

eureka:
  instance:
    hostname: courses
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
