spring:
  application:
    name: courses

server:
  port: 8091

eureka:
  instance:
    hostname: courses
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
