spring:
  application:
    name: users

server:
  port: 8090

eureka:
  instance:
    hostname: users
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# courses:
#   ribbon:
#     eureka:
#       enabled: true
#     ServerListRefreshInterval: 15000
#     NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
